[book]
title = "Ariadne's Network Notes"
description = "My notes for studying network things."
authors = ["Ariadne"]
language = "en"

[output.html]
additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/ariadne-notes/networking"