[book]
title = "Push, Pop, Swap"
description = "Ariadne's Network Studying notes."
authors = ["Ariadne"]
language = "en"

[preprocessor.svgbob]

[preprocessor.mermaid]
command = "mdbook-mermaid"     # render only code-blocks marked as "mermaid" e.g. ```mermaid

[preprocessor.gitinfo]
enable      = true
hyperlink   = true
date-format = "%A, %B %e, %Y."
time-format = "%l:%M %P UTC%Z"

[preprocessor.gitinfo.message]
footer = "Last Modified{{sep}}{{date}}{{sep}}Commit: {{hash}}"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
copy-js = true

[output.html]
mathjax-support = true
additional-css = ["theme/custom.css","theme/mermaid-lightbox.css"]
additional-js = ["theme/svg-pan-zoom.min.js","theme/mermaid-lightbox.js","theme/mermaid.min.js", "theme/mermaid-init.js","theme/editable-extras.js"]
git-repository-url = "https://github.com/ariadne-notes/pushpopswap"
